spring:
  redis:
    open: true
    database: 0
    host: localhost
    port: 6379
    password:  redisPass # password (default is empty)
    timeout: 6000MS # connection timeout time (ms)
    jedis:
      pool:
        max-active: 1000    #     Maximum connection number (no limit is limited)
        max-wait: -1MS # connection pool maximum blocking waiting time (no limit is limited)
        max-idle: 10            # Connect the maximum idle connection in the pool
        min-idle: 5              # #